import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import Providers from "./Providers";
import { Navbar } from "@/components/pages/Navbar";
import { Footer } from "@/components/pages/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` h-full antialiased`}
    >
      
      <Providers>
         <body className="min-h-full flex flex-col bg-white">
          <Navbar/>
          <div>
             {children}
             <Toaster position="top-right"/>
          </div>
          <Footer/>
          </body>
      </Providers>
     
    </html>
  );
}
